2025-10-22:12:31:20 INFO     [__main__:450] Selected Tasks: ['aime24']
2025-10-22:12:31:20 INFO     [evaluator:202] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234 | Setting fewshot manual seed to 1234
2025-10-22:12:31:20 WARNING  [evaluator:214] generation_kwargs: {'max_gen_toks': 32767} specified through cli, these settings will update set parameters in yaml tasks. Ensure 'do_sample=True' for non-greedy decoding!
2025-10-22:12:31:20 INFO     [evaluator:240] Initializing hf model, with arguments: {'pretrained': 'DeepSeek-R1/DeepSeek-R1-Distill-Qwen-7B'}
2025-10-22:12:31:20 WARNING  [accelerate.utils.other:513] Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2025-10-22:12:31:20 INFO     [models.huggingface:156] Using device 'cuda:0'
Traceback (most recent call last):
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/utils/_http.py", line 407, in hf_raise_for_status
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/DeepSeek-R1/DeepSeek-R1-Distill-Qwen-7B/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/transformers/utils/hub.py", line 479, in cached_files
    hf_hub_download(
    ~~~~~~~~~~~~~~~^
        path_or_repo_id,
        ^^^^^^^^^^^^^^^^
    ...<10 lines>...
        local_files_only=local_files_only,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/file_download.py", line 1010, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
        # Destination
    ...<14 lines>...
        force_download=force_download,
    )
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/file_download.py", line 1117, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/file_download.py", line 1658, in _raise_on_head_call_error
    raise head_call_error
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/file_download.py", line 1546, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
        url=url, proxies=proxies, timeout=etag_timeout, headers=headers, token=token, endpoint=endpoint
    )
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/file_download.py", line 1463, in get_hf_file_metadata
    r = _request_wrapper(
        method="HEAD",
    ...<5 lines>...
        timeout=timeout,
    )
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/file_download.py", line 286, in _request_wrapper
    response = _request_wrapper(
        method=method,
    ...<2 lines>...
        **params,
    )
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/file_download.py", line 310, in _request_wrapper
    hf_raise_for_status(response)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/huggingface_hub/utils/_http.py", line 457, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-68f906d8-73a8966e09f256494b62ef77;a7c8eb27-6422-4855-8156-3fd296ad281a)

Repository Not Found for url: https://huggingface.co/DeepSeek-R1/DeepSeek-R1-Distill-Qwen-7B/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated. For more details, see https://huggingface.co/docs/huggingface_hub/authentication
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/bin/lm_eval", line 7, in <module>
    sys.exit(cli_evaluate())
             ~~~~~~~~~~~~^^
  File "/fs/nexus-scratch/azheng15/research/self-improvement/Var-self-improvement/lm-evaluation-harness/lm_eval/__main__.py", line 459, in cli_evaluate
    results = evaluator.simple_evaluate(
        model=args.model,
    ...<25 lines>...
        **request_caching_args,
    )
  File "/fs/nexus-scratch/azheng15/research/self-improvement/Var-self-improvement/lm-evaluation-harness/lm_eval/utils.py", line 458, in _wrapper
    return fn(*args, **kwargs)
  File "/fs/nexus-scratch/azheng15/research/self-improvement/Var-self-improvement/lm-evaluation-harness/lm_eval/evaluator.py", line 245, in simple_evaluate
    lm = lm_eval.api.registry.get_model(model).create_from_arg_string(
        model_args,
    ...<4 lines>...
        },
    )
  File "/fs/nexus-scratch/azheng15/research/self-improvement/Var-self-improvement/lm-evaluation-harness/lm_eval/api/model.py", line 155, in create_from_arg_string
    return cls(**args, **args2)
  File "/fs/nexus-scratch/azheng15/research/self-improvement/Var-self-improvement/lm-evaluation-harness/lm_eval/models/huggingface.py", line 185, in __init__
    self._get_config(
    ~~~~~~~~~~~~~~~~^
        pretrained,
        ^^^^^^^^^^^
    ...<3 lines>...
        subfolder=subfolder,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/fs/nexus-scratch/azheng15/research/self-improvement/Var-self-improvement/lm-evaluation-harness/lm_eval/models/huggingface.py", line 567, in _get_config
    self._config = transformers.AutoConfig.from_pretrained(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        pretrained,
        ^^^^^^^^^^^
    ...<3 lines>...
        subfolder=subfolder,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/transformers/models/auto/configuration_auto.py", line 1332, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/transformers/configuration_utils.py", line 662, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/transformers/configuration_utils.py", line 721, in _get_config_dict
    resolved_config_file = cached_file(
        pretrained_model_name_or_path,
    ...<10 lines>...
        _commit_hash=commit_hash,
    )
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/transformers/utils/hub.py", line 322, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "/fs/nexus-scratch/azheng15/miniconda3/envs/mathVarRL/lib/python3.13/site-packages/transformers/utils/hub.py", line 511, in cached_files
    raise OSError(
    ...<4 lines>...
    ) from e
OSError: DeepSeek-R1/DeepSeek-R1-Distill-Qwen-7B is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `hf auth login` or by passing `token=<your_token>`
